version: '3.8' # 推荐使用较新的Compose文件格式版本

services:
  python_app:
    build:
      context: . # 指定Dockerfile所在的目录，这里是当前目录
      dockerfile: Dockerfile # 指定Dockerfile文件名
    ports:
      - "8004:7860" # 将主机上的7860端口映射到容器的7860端口
    # 使用 .env 文件来管理环境变量
    env_file:
      - .env
    # volumes:
    #   - ./data:/app/data # 如果有数据需要持久化或从主机挂载
    restart: unless-stopped # 根据需要设置重启策略
