version: '3.8'

services:
  sambanova_proxy:
    # Use pre-built image from GHCR.io (recommended)
    image: ghcr.io/caidaoli/sambanovo2api:latest
    
    # Alternative: Build from source
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   target: production
    
    ports:
      - "8000:8000"  # Updated to match the app's default port
    env_file:
      - .env
    
    # Performance optimization
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    restart: unless-stopped
    
    # Environment variables (can override .env file)
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Shanghai
    # 日志配置优化
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
