version: '3.8'

services:
  sambanova_proxy:
    build:
      context: .
      dockerfile: Dockerfile
      # 启用BuildKit以获得更好的构建性能
      target: production
    ports:
      - "8004:7860"
    env_file:
      - .env
    # 性能优化配置
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    # 健康检查
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:7860/info', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    # 日志配置优化
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
